apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: iaa5hvo8b-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: iaa5hvo8b-nodejs 
  name: iaa5hvo8b-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: iaa5hvo8b-nodejs 
